version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rpg
      - JWT_SECRET=your_jwt_secret_here
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./src:/usr/src/app/src  # Add this to ensure src files are watched
      - /usr/src/app/node_modules
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rpg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: