begin;

set search_path = public;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create table public.users (
  id integer generated by default as identity primary key,
  username varchar(50) not null unique,
  password varchar(255) not null,
  role varchar(20) not null default 'user',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint users_role_check check (role in ('user', 'staffer', 'master', 'admin'))
);

create table public.races (
  id integer generated by default as identity primary key,
  name varchar(100) not null unique,
  description text not null,
  image varchar,
  "healthBonus" integer not null default 0,
  "manaBonus" integer not null default 0,
  "speedBonus" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "focusBonus" integer not null default 0,
  "controlBonus" integer not null default 0,
  "resilienceBonus" integer not null default 0,
  "instinctBonus" integer not null default 0,
  "presenceBonus" integer not null default 0,
  "forceBonus" integer not null default 0,
  "isPlayable" boolean not null default true
);

create table public.maps (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  "imageUrl" varchar not null,
  "isMainMap" boolean not null default false,
  "createdAt" timestamptz not null default now()
);

create table public.locations (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  description text not null,
  "xCoordinate" integer not null,
  "yCoordinate" integer not null,
  "mapId" integer not null
);

create table public.skill_branches (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  uses integer not null default 0
);

create table public.skill_types (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  description text
);

create table public.skills (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  description text,
  "branchId" integer not null,
  "typeId" integer not null,
  "basePower" integer not null,
  duration integer not null,
  activation varchar(255) not null,
  "requiredStats" jsonb,
  "scalingStats" jsonb default '[]'::jsonb,
  "aetherCost" integer not null,
  "skillPointCost" integer not null default 1,
  target varchar(10) not null default 'other',
  rank integer not null,
  "parentSkillId" integer,
  "isPassive" boolean not null,
  "unlockConditions" jsonb not null default '{"uses":0,"combinations":[]}'::jsonb,
  "mutationOptions" jsonb,
  "comboTag" varchar(50),
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint skills_target_check check (target in ('self', 'other', 'none', 'any'))
);

create table public.characters (
  id integer generated by default as identity primary key,
  "userId" integer,
  name varchar(50) not null,
  surname varchar(50) not null,
  "imageUrl" varchar(255),
  age integer not null,
  gender varchar(20) not null,
  "raceId" integer not null,
  stats jsonb not null default '{}'::jsonb,
  "isActive" boolean not null default false,
  background text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  experience double precision not null default 0,
  "skillPoints" integer not null default 5,
  rank integer not null default 1,
  "statPoints" integer not null default 0,
  "isNPC" boolean not null default false,
  "createdBy" integer
);

create table public.character_skills (
  "characterId" integer not null,
  "skillId" integer not null,
  uses integer not null default 0,
  "unlockedAt" timestamptz not null default now(),
  rank integer not null default 1,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  primary key ("characterId", "skillId")
);

create table public.character_skill_branches (
  id integer generated by default as identity primary key,
  "characterId" integer not null,
  "branchId" integer not null,
  uses integer not null default 0,
  rank integer not null default 1,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.sessions (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  "locationId" integer not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "isActive" boolean not null default true,
  "isEvent" boolean not null default false,
  "eventId" integer,
  status varchar(20) not null default 'open',
  "expirationTime" timestamptz,
  constraint sessions_status_check check (status in ('open', 'closed', 'frozen'))
);

create table public.events (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  type varchar(20) not null,
  description text,
  "locationId" integer not null,
  "sessionId" integer,
  status varchar(20) not null default 'active',
  "createdBy" integer not null,
  "closedBy" integer,
  "createdAt" timestamptz not null default now(),
  "closedAt" timestamptz,
  "eventData" jsonb,
  constraint events_type_check check (type in ('lore', 'duel', 'quest')),
  constraint events_status_check check (status in ('active', 'closed'))
);

create table public.session_participants (
  id integer generated by default as identity primary key,
  "sessionId" integer not null,
  "characterId" integer not null,
  "joinedAt" timestamptz not null default now()
);

create table public.chat_messages (
  id integer generated by default as identity primary key,
  "userId" integer not null,
  "characterId" integer,
  username varchar(100) not null,
  message text not null,
  "createdAt" timestamptz not null default now(),
  "skillId" integer,
  "skillName" varchar(100),
  "skillBranch" varchar(100),
  "skillType" varchar(100),
  "skillOutput" integer,
  "skillRoll" varchar(100),
  "locationId" integer
);

create table public.combat_rounds (
  id integer generated by default as identity primary key,
  "roundNumber" integer not null,
  "locationId" integer not null,
  "sessionId" integer,
  "eventId" integer,
  status varchar(20) not null default 'active',
  "createdBy" integer not null,
  "resolvedBy" integer,
  "resolutionData" jsonb,
  "createdAt" timestamptz not null default now(),
  "resolvedAt" timestamptz,
  constraint combat_rounds_status_check check (status in ('active', 'resolved', 'cancelled'))
);

create table public.combat_actions (
  id integer generated by default as identity primary key,
  "roundId" integer not null,
  "characterId" integer not null,
  "skillId" integer not null,
  "targetId" integer,
  "finalOutput" integer not null,
  "outcomeMultiplier" numeric(3, 2) not null,
  "rollQuality" varchar(20) not null,
  "skillData" jsonb,
  "characterData" jsonb,
  "targetData" jsonb,
  "submittedAt" timestamptz not null default now(),
  processed boolean not null default false,
  "clashResult" jsonb,
  constraint combat_actions_roll_quality_check check ("rollQuality" in ('Poor', 'Standard', 'Critical'))
);

create table public.engine_logs (
  id integer generated by default as identity primary key,
  "sessionId" integer not null,
  "locationId" integer not null,
  type varchar(20) not null,
  actor varchar(100) not null,
  target varchar(100),
  skill varchar(100),
  damage integer,
  effects jsonb,
  details text not null,
  "engineData" jsonb,
  "createdAt" timestamptz not null default now(),
  constraint engine_logs_type_check check (type in ('skill_use', 'clash', 'damage', 'effect'))
);

create table public.combat_constants (
  id integer generated by default as identity primary key,
  "constantKey" varchar(100) not null unique,
  "displayName" varchar(200) not null,
  description text,
  value numeric(10, 4) not null,
  category varchar(50) not null,
  "minValue" numeric(10, 4),
  "maxValue" numeric(10, 4),
  "isPercentage" boolean not null default false,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint combat_constants_category_check check (category in ('hp_system', 'aether_system', 'damage_system', 'mastery_system', 'outcome_system')),
  constraint combat_constants_value_range_check check ("minValue" is null or "maxValue" is null or "maxValue" >= "minValue")
);

create table public.mastery_tiers (
  id integer generated by default as identity primary key,
  tier integer not null,
  "tierName" varchar(100) not null,
  "usesRequired" integer not null default 0,
  multiplier numeric(5, 2) not null default 1.00,
  description text,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.ranks (
  level integer primary key,
  "requiredExperience" integer not null,
  "statPoints" integer not null default 0,
  "skillPoints" integer not null default 0,
  "aetherPercent" double precision not null default 0,
  "hpPercent" double precision not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.skill_validation_rules (
  id integer generated by default as identity primary key,
  "skillType" varchar(50) not null,
  "skillSubtype" varchar(50) not null,
  "minBasePower" integer not null default 0,
  "maxBasePower" integer not null default 100,
  "minAetherCost" integer not null default 0,
  "maxAetherCost" integer not null default 100,
  description text,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint skill_validation_rules_type_check check ("skillType" in ('attack', 'defence', 'counter', 'buff_debuff', 'healing')),
  constraint skill_validation_rules_power_range_check check ("maxBasePower" >= "minBasePower"),
  constraint skill_validation_rules_aether_range_check check ("maxAetherCost" >= "minAetherCost")
);

create table public.stat_definitions (
  id integer generated by default as identity primary key,
  "internalName" varchar(50) not null unique,
  "displayName" varchar(100) not null,
  description text,
  category varchar(20) not null,
  "defaultValue" integer not null default 0,
  "maxValue" integer default 100,
  "minValue" integer not null default 0,
  "isActive" boolean not null default true,
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint stat_definitions_category_check check (category in ('primary_stat', 'resource', 'scaling_stat')),
  constraint stat_definitions_value_range_check check ("maxValue" is null or "maxValue" >= "minValue")
);

create table public.wiki_sections (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  slug varchar(100) not null unique,
  description text,
  position integer not null default 0,
  "isActive" boolean not null default true,
  "createdBy" integer not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table public.wiki_entries (
  id integer generated by default as identity primary key,
  "sectionId" integer not null,
  title varchar(200) not null,
  slug varchar(200) not null,
  content text not null,
  excerpt text,
  tags jsonb default '[]'::jsonb,
  "isPublished" boolean not null default true,
  position integer not null default 0,
  "parentEntryId" integer,
  level integer not null default 1,
  "viewCount" integer not null default 0,
  "createdBy" integer not null,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint wiki_entries_level_check check (level between 1 and 4)
);

alter table public.locations
  add constraint locations_map_id_fkey foreign key ("mapId") references public.maps(id) on delete cascade;

alter table public.skills
  add constraint skills_branch_id_fkey foreign key ("branchId") references public.skill_branches(id),
  add constraint skills_type_id_fkey foreign key ("typeId") references public.skill_types(id),
  add constraint skills_parent_skill_id_fkey foreign key ("parentSkillId") references public.skills(id);

alter table public.characters
  add constraint characters_user_id_fkey foreign key ("userId") references public.users(id) on delete cascade,
  add constraint characters_race_id_fkey foreign key ("raceId") references public.races(id) on delete cascade,
  add constraint characters_created_by_fkey foreign key ("createdBy") references public.users(id) on delete set null;

alter table public.character_skills
  add constraint character_skills_character_id_fkey foreign key ("characterId") references public.characters(id) on delete cascade,
  add constraint character_skills_skill_id_fkey foreign key ("skillId") references public.skills(id) on delete cascade;

alter table public.character_skill_branches
  add constraint character_skill_branches_character_id_fkey foreign key ("characterId") references public.characters(id) on delete cascade,
  add constraint character_skill_branches_branch_id_fkey foreign key ("branchId") references public.skill_branches(id) on delete cascade;

alter table public.sessions
  add constraint sessions_location_id_fkey foreign key ("locationId") references public.locations(id) on delete cascade;

alter table public.events
  add constraint events_location_id_fkey foreign key ("locationId") references public.locations(id) on delete cascade,
  add constraint events_session_id_fkey foreign key ("sessionId") references public.sessions(id) on delete set null,
  add constraint events_created_by_fkey foreign key ("createdBy") references public.users(id),
  add constraint events_closed_by_fkey foreign key ("closedBy") references public.users(id) on delete set null;

alter table public.sessions
  add constraint sessions_event_id_fkey foreign key ("eventId") references public.events(id) on delete set null;

alter table public.session_participants
  add constraint session_participants_session_id_fkey foreign key ("sessionId") references public.sessions(id) on delete cascade,
  add constraint session_participants_character_id_fkey foreign key ("characterId") references public.characters(id) on delete cascade;

alter table public.chat_messages
  add constraint chat_messages_location_id_fkey foreign key ("locationId") references public.locations(id) on delete cascade,
  add constraint chat_messages_user_id_fkey foreign key ("userId") references public.users(id),
  add constraint chat_messages_character_id_fkey foreign key ("characterId") references public.characters(id) on delete set null,
  add constraint chat_messages_skill_id_fkey foreign key ("skillId") references public.skills(id) on delete set null;

alter table public.combat_rounds
  add constraint combat_rounds_location_id_fkey foreign key ("locationId") references public.locations(id) on delete cascade,
  add constraint combat_rounds_session_id_fkey foreign key ("sessionId") references public.sessions(id) on delete set null,
  add constraint combat_rounds_event_id_fkey foreign key ("eventId") references public.events(id) on delete set null,
  add constraint combat_rounds_created_by_fkey foreign key ("createdBy") references public.users(id),
  add constraint combat_rounds_resolved_by_fkey foreign key ("resolvedBy") references public.users(id) on delete set null;

alter table public.combat_actions
  add constraint combat_actions_round_id_fkey foreign key ("roundId") references public.combat_rounds(id) on delete cascade,
  add constraint combat_actions_character_id_fkey foreign key ("characterId") references public.characters(id),
  add constraint combat_actions_skill_id_fkey foreign key ("skillId") references public.skills(id),
  add constraint combat_actions_target_id_fkey foreign key ("targetId") references public.characters(id) on delete set null;

alter table public.engine_logs
  add constraint engine_logs_session_id_fkey foreign key ("sessionId") references public.sessions(id) on delete cascade,
  add constraint engine_logs_location_id_fkey foreign key ("locationId") references public.locations(id) on delete cascade;

alter table public.wiki_sections
  add constraint wiki_sections_created_by_fkey foreign key ("createdBy") references public.users(id) on delete cascade;

alter table public.wiki_entries
  add constraint wiki_entries_section_id_fkey foreign key ("sectionId") references public.wiki_sections(id) on delete cascade,
  add constraint wiki_entries_created_by_fkey foreign key ("createdBy") references public.users(id) on delete cascade,
  add constraint wiki_entries_parent_entry_id_fkey foreign key ("parentEntryId") references public.wiki_entries(id);

create unique index "IDX_CHARACTER_SKILL_BRANCH_UNIQUE" on public.character_skill_branches ("characterId", "branchId");
create index "IDX_CHARACTER_SKILL_CHARACTER" on public.character_skills ("characterId");
create index "IDX_CHARACTER_SKILL_SKILL" on public.character_skills ("skillId");
create index "IDX_COMBAT_ACTION_ROUND" on public.combat_actions ("roundId");
create index "IDX_COMBAT_ACTION_CHARACTER" on public.combat_actions ("characterId");
create unique index "IDX_COMBAT_ACTION_UNIQUE_PER_ROUND" on public.combat_actions ("roundId", "characterId");
create index "IDX_COMBAT_CONSTANT_CATEGORY" on public.combat_constants (category);
create index "IDX_COMBAT_CONSTANT_ACTIVE" on public.combat_constants ("isActive");
create index "IDX_COMBAT_CONSTANT_KEY" on public.combat_constants ("constantKey");
create index "IDX_COMBAT_ROUND_LOCATION" on public.combat_rounds ("locationId");
create index "IDX_COMBAT_ROUND_SESSION" on public.combat_rounds ("sessionId");
create index "IDX_COMBAT_ROUND_EVENT" on public.combat_rounds ("eventId");
create index "IDX_ENGINE_LOG_SESSION" on public.engine_logs ("sessionId");
create index "IDX_ENGINE_LOG_LOCATION" on public.engine_logs ("locationId");
create index "IDX_ENGINE_LOG_TYPE" on public.engine_logs (type);
create index "IDX_EVENT_LOCATION" on public.events ("locationId");
create index "IDX_EVENT_SESSION" on public.events ("sessionId");
create index "IDX_EVENT_STATUS" on public.events (status);
create index "IDX_MASTERY_TIER" on public.mastery_tiers (tier);
create index "IDX_MASTERY_ACTIVE" on public.mastery_tiers ("isActive");
create index "IDX_MASTERY_USES" on public.mastery_tiers ("usesRequired");
create index "IDX_SKILL_VALIDATION_TYPE" on public.skill_validation_rules ("skillType");
create index "IDX_SKILL_VALIDATION_SUBTYPE" on public.skill_validation_rules ("skillSubtype");
create index "IDX_SKILL_VALIDATION_ACTIVE" on public.skill_validation_rules ("isActive");
create unique index "IDX_SKILL_VALIDATION_TYPE_SUBTYPE" on public.skill_validation_rules ("skillType", "skillSubtype");
create index "IDX_STAT_DEFINITION_CATEGORY" on public.stat_definitions (category);
create index "IDX_STAT_DEFINITION_ACTIVE" on public.stat_definitions ("isActive");
create unique index "IDX_WIKI_ENTRY_SECTION_SLUG" on public.wiki_entries ("sectionId", slug);
create index "IDX_WIKI_ENTRY_SECTION_POSITION" on public.wiki_entries ("sectionId", position);
create index "IDX_WIKI_ENTRY_PUBLISHED" on public.wiki_entries ("isPublished");
create index "IDX_WIKI_ENTRY_TAGS" on public.wiki_entries using gin (tags);
create index "IDX_WIKI_ENTRY_PARENT" on public.wiki_entries ("parentEntryId");
create index "IDX_WIKI_ENTRY_LEVEL" on public.wiki_entries (level);
create unique index "IDX_WIKI_SECTION_SLUG" on public.wiki_sections (slug);
create index "IDX_WIKI_SECTION_POSITION" on public.wiki_sections (position);

create unique index sessions_event_id_unique on public.sessions ("eventId") where "eventId" is not null;
create unique index session_participants_session_character_unique on public.session_participants ("sessionId", "characterId");
create index locations_map_id_idx on public.locations ("mapId");
create index skills_branch_id_idx on public.skills ("branchId");
create index skills_type_id_idx on public.skills ("typeId");
create index skills_parent_skill_id_idx on public.skills ("parentSkillId");
create index characters_user_id_idx on public.characters ("userId");
create index characters_race_id_idx on public.characters ("raceId");
create index characters_created_by_idx on public.characters ("createdBy");
create index sessions_location_id_idx on public.sessions ("locationId");
create index sessions_event_id_idx on public.sessions ("eventId");
create index session_participants_session_id_idx on public.session_participants ("sessionId");
create index session_participants_character_id_idx on public.session_participants ("characterId");
create index chat_messages_location_id_created_at_idx on public.chat_messages ("locationId", "createdAt");
create index chat_messages_user_id_created_at_idx on public.chat_messages ("userId", "createdAt");
create index combat_actions_target_id_idx on public.combat_actions ("targetId");
create index wiki_sections_created_by_idx on public.wiki_sections ("createdBy");
create index wiki_entries_created_by_idx on public.wiki_entries ("createdBy");

create trigger set_users_updated_at before update on public.users for each row execute function public.set_updated_at();
create trigger set_races_updated_at before update on public.races for each row execute function public.set_updated_at();
create trigger set_skills_updated_at before update on public.skills for each row execute function public.set_updated_at();
create trigger set_characters_updated_at before update on public.characters for each row execute function public.set_updated_at();
create trigger set_character_skills_updated_at before update on public.character_skills for each row execute function public.set_updated_at();
create trigger set_character_skill_branches_updated_at before update on public.character_skill_branches for each row execute function public.set_updated_at();
create trigger set_sessions_updated_at before update on public.sessions for each row execute function public.set_updated_at();
create trigger set_combat_constants_updated_at before update on public.combat_constants for each row execute function public.set_updated_at();
create trigger set_mastery_tiers_updated_at before update on public.mastery_tiers for each row execute function public.set_updated_at();
create trigger set_ranks_updated_at before update on public.ranks for each row execute function public.set_updated_at();
create trigger set_skill_validation_rules_updated_at before update on public.skill_validation_rules for each row execute function public.set_updated_at();
create trigger set_stat_definitions_updated_at before update on public.stat_definitions for each row execute function public.set_updated_at();
create trigger set_wiki_sections_updated_at before update on public.wiki_sections for each row execute function public.set_updated_at();
create trigger set_wiki_entries_updated_at before update on public.wiki_entries for each row execute function public.set_updated_at();

commit;
